config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  
  resources :tops do
    
    collection do
      get 'company_login_form' 
      get 'user_login_form'
      post 'company_login'
      post 'user_login'
    end
  
  end
  
  resources :companies do
    
     collection do
       get 'trade'
       get 'point'
       post 'transfer'
     end
     
     member do
       post 'ship'
       post 'reply_ship'
     end
      
  end
  
  resources :users do 

    collection do
      get 'save'
      get 'paytment'
      get 'trade'
    end
    
    member do
      post 'point'
      post 'reply_point'
    end
  
  end
  
  resources :topics
  
  resources :posts 
  
  resources :replies do
    
    member do
      get 'new'
    end
  
  end
  
  resources :card do
    
    collection do
      post 'delete'
    end
    
  end
  
  post 'likes/create' => 'likes#create'
  
  resources :payments do
    
    collection do
      get 'done'
      post 'pay'
      post 'topic_pay'
      post 'like_pay'
    end
    
    member do
      get 'detail'
      get 'topic_detail'
      get 'like_detail'
    end
    
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
    validates :company_name, {uniqueness: true}
    validates :company_name, {presence: true}
    validates :email, {presence: true, uniqueness: true}
    #validates :email, format: { with:/\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@[a-zA-Z0-9][a-zA-Z0-9\.-]+\z/ }
    validates :address, {presence: true, uniqueness: true}
    validates :password, {presence: true}
    #validates :password, format: { with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/}
    
    has_many :replies
    has_many :topics
    
    mount_uploader :profile_image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :topic
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, length: {maximum:140}
    
    belongs_to :user
    has_many :replies
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :post
    belongs_to :company
    
    mount_uploader :image_name, ImageUploader
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :company
    has_many :likes
    
    
    mount_uploader :image_name, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  
  after_create :assign_admin_role
  after_create :assign_default_role
  
   def assign_admin_role
     self.add_role(:admin) if self.name == 'admin'
   end
   
   def assign_default_role
     self.add_role(:guest) if self.roles.blank?
   end
  
    #validates :user_name, {uniqueness: true, presence: true}
    #validates :name, {presence: true, uniqueness: true}
    #validates :email, {presence: true, uniqueness: true}
    #validates :email, format: { with:/\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@[a-zA-Z0-9][a-zA-Z0-9\.-]+\z/ }
    #validates :address, {presence: true, uniqueness: true}
    #validates :password, {presence: true}
    #validates :password, format: { with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/}
    
    has_many :posts
    
    has_many :likes
    
    def posts
       return Post.where(user_id: self.id) 
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
  
  def company_login_form
  end
  
  def company_login
     @company = Company.find_by(email: params[:email], password: params[:password])
    if @company
      session[:company_id] = @company.id
      redirect_to("/companies/#{@company.id}")
    else
      
    end
  end
  
  def company_logout
    session[:company_id] = nil
    redirect_to("/top/index")
  end
  
  def user_login_form
  end
  
  def user_login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to("/users/#{@user.id}")
    end
  end
  
  def user_logout
    session[:user_id] = nil
    redirect_to("/top/index")
  end
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
  
  def company_login_form
  end
  
  def company_login
     @company = Company.find_by(email: params[:email], password: params[:password])
    if @company
      session[:company_id] = @company.id
      redirect_to("/companies/show")
    else
      
    end
  end
  
  def user_login_form
  end
  
  def user_login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to("/users/show")
    end
  end
  
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/top/company_login_form.html.erb
<header>
  <div class="top-header">
    <div class="row">
      <div class="col-md-offset-2 col-md-2 logo">
        <%= link_to "地魚マーケット","/top/index", class: 'logo' %>
      </div>
      <div class="col-md-2 l-btn">
      　<%= link_to "業者様ログイン","/top/company_login", class: 'btn-l'%>
      </div>
      <div class="col-md-2 l-btn">       
        <%= link_to "お客様ログイン","/top/user_login", class: 'btn-l'%>
      </div>
    </div>
  </div>
</header>
<div class="top-wrapper">
  <%= form_tag("/company_login") do %>
    <div class="c_login col-md-offset-5 col-md-2">      
    <p class='text-white'>メールアドレス</p>
    <input name="email" >
    <p class='text-white'>パスワード</p>
    <input type="password" name="password">
    <p>
    <input type="submit" value="ログイン">
    </p>
    </div>  
  <% end %>
</div>

app/views/top/index.html.erb
<header>
  <div class="top-header">
    <div class="row">
      <div class="col-md-offset-2 col-md-2 logo">
        <%= link_to "地魚マーケット","/top/index", class: 'logo' %>
      </div>
      <div class="col-md-2 l-btn">
      　<%= link_to "業者様ログイン","/top/company_login", class: 'btn-l'%>
      </div>
      <div class="col-md-2 l-btn">       
        <%= link_to "お客様ログイン","/top/user_login", class: 'btn-l'%>
      </div>
    </div>
  </div>
</header>
<div class="top-wrapper">
  <div class="text-center">
    <div class="container top-hero-container">
      <div class="navigation text-center">
        <p>新規会員登録はこちら</p>
      </div>
      <div class="row">
        <div class="col-md-offset-4 col-md-2 button">
          <%= link_to '業者様', companies_new_path , class: 'btn' %>
        </div>
        <div class="col-md-2 button">
          <%= link_to 'お客様', users_new_path , class: 'btn' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/top/user_login_form.html.erb
<header>
  <div class="top-header">
    <div class="row">
      <div class="col-md-offset-2 col-md-2 logo">
        <%= link_to "地魚マーケット","/top/index", class: 'logo' %>
      </div>
      <div class="col-md-2 l-btn">
      　<%= link_to "業者様ログイン","/top/company_login", class: 'btn-l'%>
      </div>
      <div class="col-md-2 l-btn">       
        <%= link_to "お客様ログイン","/top/user_login", class: 'btn-l'%>
      </div>
    </div>
  </div>
</header>
<div class="top-wrapper">
  <%= form_tag("/user_login") do %>
    <div class="c_login col-md-offset-5 col-md-2">
      <p class='text-white'>メールアドレス</p>
      <input name="email" >
      <p class='text-white'>パスワード</p>
      <input type="password" name="password">
      <p>
      <input type="submit" value="ログイン">
      </p>
    </div>  
  <% end %>
</div>

app/views/tops/company_login_form.html.erb
<header>
  <div class="top-header">
    <div class="row">
      <div class="col-md-offset-2 col-md-2 logo">
        <%= link_to "地魚マーケット","/tops", class: 'logo' %>
      </div>
      <div class="col-md-2 l-btn">
      　<%= link_to "業者様ログイン","/tops/company_login_form", class: 'btn-l'%>
      </div>
      <div class="col-md-2 l-btn">       
        <%= link_to "お客様ログイン","/tops/user_login_form", class: 'btn-l'%>
      </div>
    </div>
  </div>
</header>
<div class="top-wrapper">
  <%= form_tag("/tops/company_login") do %>
    <div class="c_login col-md-offset-5 col-md-2">      
    <p class='text-white'>メールアドレス</p>
    <input name="email" >
    <p class='text-white'>パスワード</p>
    <input type="password" name="password">
    <p>
    <input type="submit" value="ログイン">
    </p>
    </div>  
  <% end %>
</div>

app/views/tops/index.html.erb
<header>
  <div class="top-header">
    <div class="row">
      <div class="col-md-offset-2 col-md-2 logo">
        <%= link_to "地魚マーケット","/tops", class: 'logo' %>
      </div>
      <div class="col-md-2 l-btn">
      　<%= link_to "業者様ログイン","/tops/company_login_form", class: 'btn-l'%>
      </div>
      <div class="col-md-2 l-btn">       
        <%= link_to "お客様ログイン","/tops/user_login_form", class: 'btn-l'%>
      </div>
    </div>
  </div>
</header>
<div class="top-wrapper">
  <div class="text-center">
    <div class="container top-hero-container">
      <div class="navigation text-center">
        <p>新規会員登録はこちら</p>
      </div>
      <div class="row">
        <div class="col-md-offset-4 col-md-2 button">
          <%= link_to '業者様', "/companies/new" , class: 'btn' %>
        </div>
        <div class="col-md-2 button">
          <%= link_to 'お客様', "/users/new" , class: 'btn' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tops/user_login_form.html.erb
<header>
  <div class="top-header">
    <div class="row">
      <div class="col-md-offset-2 col-md-2 logo">
        <%= link_to "地魚マーケット","/tops", class: 'logo' %>
      </div>
      <div class="col-md-2 l-btn">
      　<%= link_to "業者様ログイン","/tops/company_login_form", class: 'btn-l'%>
      </div>
      <div class="col-md-2 l-btn">       
        <%= link_to "お客様ログイン","/tops/user_login_form", class: 'btn-l'%>
      </div>
    </div>
  </div>
</header>
<div class="top-wrapper">
  <%= form_tag("/tops/user_login") do %>
    <div class="c_login col-md-offset-5 col-md-2">
      <p class='text-white'>メールアドレス</p>
      <input name="email" >
      <p class='text-white'>パスワード</p>
      <input type="password" name="password">
      <p>
      <input type="submit" value="ログイン">
      </p>
    </div>  
  <% end %>
</div>