config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  
  resources :tops do
    
    collection do
      get 'company_login_form' 
      get 'user_login_form'
      post 'company_login'
      post 'user_login'
    end
  
  end
  
  resources :companies do
    
     collection do
       get 'trade'
       get 'point'
       post 'transfer'
     end
     
     member do
       post 'ship'
       post 'reply_ship'
     end
      
  end
  
  resources :users do 

    collection do
      get 'save'
      get 'paytment'
      get 'trade'
    end
    
    member do
      post 'point'
      post 'reply_point'
    end
  
  end
  
  resources :topics
  
  resources :posts 
  
  resources :replies do
    
    member do
      get 'new'
    end
  
  end
  
  resources :card do
    
    collection do
      post 'delete'
    end
    
  end
  
  post 'likes/create' => 'likes#create'
  
  resources :payments do
    
    collection do
      get 'done'
      post 'pay'
      post 'topic_pay'
      post 'like_pay'
    end
    
    member do
      get 'detail'
      get 'topic_detail'
      get 'like_detail'
    end
    
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
    validates :company_name, {uniqueness: true}
    validates :company_name, {presence: true}
    validates :email, {presence: true, uniqueness: true}
    #validates :email, format: { with:/\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@[a-zA-Z0-9][a-zA-Z0-9\.-]+\z/ }
    validates :address, {presence: true, uniqueness: true}
    validates :password, {presence: true}
    #validates :password, format: { with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/}
    
    has_many :replies
    has_many :topics
    
    mount_uploader :profile_image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :topic
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, length: {maximum:140}
    
    belongs_to :user
    has_many :replies
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :post
    belongs_to :company
    
    mount_uploader :image_name, ImageUploader
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :company
    has_many :likes
    
    
    mount_uploader :image_name, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  
  after_create :assign_admin_role
  after_create :assign_default_role
  
   def assign_admin_role
     self.add_role(:admin) if self.name == 'admin'
   end
   
   def assign_default_role
     self.add_role(:guest) if self.roles.blank?
   end
  
    #validates :user_name, {uniqueness: true, presence: true}
    #validates :name, {presence: true, uniqueness: true}
    #validates :email, {presence: true, uniqueness: true}
    #validates :email, format: { with:/\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@[a-zA-Z0-9][a-zA-Z0-9\.-]+\z/ }
    #validates :address, {presence: true, uniqueness: true}
    #validates :password, {presence: true}
    #validates :password, format: { with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/}
    
    has_many :posts
    
    has_many :likes
    
    def posts
       return Post.where(user_id: self.id) 
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = Topic.new
    @topic.company_id = current_company.id
    @topic.content = params[:content]
    @topic.price = params[:price]
    @topic.image_name = params[:image_name]
    #binding.pry
    if @topic.save
      flash[:notice] = "送信が完了しました"
      redirect_to("/companies/show")
    else
      render :new
    end
  end
  
  def show
    @topics = Topic.all.order(created_at: :desc)
  end
  
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
  <h>会社名</h><br>
    <%= topic.company.company_name %><br>
  <h>画像</h><br>
    <img src ="<%= topic.image_name %>"><br>
  <h>投稿内容</h><br>
    <%= topic.content %><br>
  <h>値段</h><br>
    <%= topic.price %><br>
  <h>日時</h>
    <%= topic.created_at.strftime('%Y/%m/%d') %><br>
    <% if Like.find_by(user_id: current_user.id, topic_id: topic.id) %>
        <%= 'いいね済み！' %>
    <% else %>
        <%= link_to likes_create_path(topic_id: topic.id), method: :post do %>
        <%= 'いいねしますか？' %>
    <% end %>
    <% end %><br>
    <% if topic.buyer_id.nil? %> 
      <%= link_to("購入する","/buy/#{topic.id}/topic_detail") %><br>
    <% else %>
      <h>売り切れました！</h><br>
    <% end %>
<% end %>

app/views/topics/new.html.erb
<div class="reply text-center">
    <%= form_tag("/topics", method: :post, multipart: true) do %>
      <h>商品詳細</h><br>
      <textarea name="content"></textarea><br>
      <h>お値段</h><br>
      <input name="price"><br>
      <%= file_field_tag :image_name %>
      <input type="submit" name="送信" >
    <% end %>
</div>

app/views/topics/show.html.erb
<% @topics.each do |topic| %>
  <h>会社名</h><br>
    <%= topic.company.company_name %><br>
  <h>画像</h><br>
    <img src ="<%= topic.image_name %>"><br>
  <h>投稿内容</h><br>
    <%= topic.content %><br>
  <h>値段</h><br>
    <%= topic.price %><br>
  <h>日時</h>
    <%= topic.created_at.strftime("%Y-%m-%d %H:%M") %><br>
    <% if Like.find_by(user_id: current_user.id, topic_id: topic.id) %>
        <%= 'いいね済み！' %>
    <% else %>
        <%= link_to likes_create_path(topic_id: topic.id), method: :post do %>
        <%= 'いいねしますか？' %>
    <% end %>
    <% end %><br>
    <% if topic.buyer_id.nil? %> 
      <%= link_to("購入する","/payments/#{topic.id}/topic_detail") %><br>
    <% else %>
      <h>売り切れました！</h><br>
    <% end %>
<% end %>