config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  
  resources :tops do
    
    collection do
      get 'company_login_form' 
      get 'user_login_form'
      post 'company_login'
      post 'user_login'
    end
  
  end
  
  resources :companies do
    
     collection do
       get 'trade'
       get 'point'
       post 'transfer'
     end
     
     member do
       post 'ship'
       post 'reply_ship'
     end
      
  end
  
  resources :users do 

    collection do
      get 'save'
      get 'paytment'
      get 'trade'
    end
    
    member do
      post 'point'
      post 'reply_point'
    end
  
  end
  
  resources :topics
  
  resources :posts 
  
  resources :replies do
    
    member do
      get 'new'
    end
  
  end
  
  resources :card do
    
    collection do
      post 'delete'
    end
    
  end
  
  post 'likes/create' => 'likes#create'
  
  resources :payments do
    
    collection do
      get 'done'
      post 'pay'
      post 'topic_pay'
      post 'like_pay'
    end
    
    member do
      get 'detail'
      get 'topic_detail'
      get 'like_detail'
    end
    
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
    validates :company_name, {uniqueness: true}
    validates :company_name, {presence: true}
    validates :email, {presence: true, uniqueness: true}
    #validates :email, format: { with:/\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@[a-zA-Z0-9][a-zA-Z0-9\.-]+\z/ }
    validates :address, {presence: true, uniqueness: true}
    validates :password, {presence: true}
    #validates :password, format: { with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/}
    
    has_many :replies
    has_many :topics
    
    mount_uploader :profile_image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :topic
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, length: {maximum:140}
    
    belongs_to :user
    has_many :replies
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :post
    belongs_to :company
    
    mount_uploader :image_name, ImageUploader
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :company
    has_many :likes
    
    
    mount_uploader :image_name, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  
  after_create :assign_admin_role
  after_create :assign_default_role
  
   def assign_admin_role
     self.add_role(:admin) if self.name == 'admin'
   end
   
   def assign_default_role
     self.add_role(:guest) if self.roles.blank?
   end
  
    #validates :user_name, {uniqueness: true, presence: true}
    #validates :name, {presence: true, uniqueness: true}
    #validates :email, {presence: true, uniqueness: true}
    #validates :email, format: { with:/\A[a-zA-Z0-9_\#!$%&`'*+\-{|}~^\/=?\.]+@[a-zA-Z0-9][a-zA-Z0-9\.-]+\z/ }
    #validates :address, {presence: true, uniqueness: true}
    #validates :password, {presence: true}
    #validates :password, format: { with:/\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/}
    
    has_many :posts
    
    has_many :likes
    
    def posts
       return Post.where(user_id: self.id) 
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = Company.new
  end
  
  def create
    @company = Company.new(company_name: params[:company_name], 
                           email: params[:email], 
                           phone_number: params[:phone_number],
                           address: params[:address], 
                           password: params[:password],
                           image_name: params[:image_name] )
    if @company.save
      session[:company_id] = @company.id
      redirect_to("/companies/#{@company.id}")
    end
  end
  
  def show
    @company = Company.find_by(id: params[:id])
    @topics = Topic.where(company_id: current_company.id).order(created_at: :desc)
  end
  
  def edit
    @company = Company.find_by(id: current_company.id)
  end
  
  def update
    @company = Company.find_by(id: current_company.id)
    @company.profile = params[:profile]
    @company.profile_image = params[:profile_image]
    if @company.save
      redirect_to("/companies/show")
    end
  end
  
  def trade
    @topics = Topic.where(company_id: current_company.id).where.not(buyer_id: nil).order(created_at: :desc)
    @replies = Reply.where(company_id: current_company.id).where.not(buyer_id: nil).order(created_at: :desc)
  end
  
  def ship
    @topic = Topic.find_by(id: params[:id])
    @topic.address = nil
    if @topic.save
      flash[:notice] = "発送通知が完了しました"
      redirect_to("/companies/show")
    else
      render :new
    end
  end
  
  def reply_ship
    @reply = Reply.find_by(id: params[:id])
    @reply.address = nil
    if @reply.save
      flash[:notice] = "発送通知が完了しました"
      redirect_to("/companies/show")
    else
      render :new
    end
  end
  
  def point
    @company = Company.find_by(id: current_company.id)
    @topics = Topic.where(id: current_company.id)
    @replies = Reply.where(id: current_company.id)
    @records = Record.where(company_id: current_company.id)
  end
  
  def transfer
    @company = Company.find_by(id: current_company.id)
    @record = Record.new
    @record.company_id = current_company.id 
    @record.record = @company.point
    @record.save
    @company.point = nil
    if @company.save
      flash[:notice] = "振り込み依頼が完了しました"
      redirect_to("/companies/show")
    end
  end
  
  def destroy
    session[:company_id] = nil
    redirect_to("/tops")
  end
  
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/edit.html.erb
<%= form_tag("/companies/update", method: :patch, multipart: true) do %><br>
  <h>プロフィール画像の設定</h><br>
  <%= file_field_tag :profile_image %><br>
  <h>自己紹介文</h><br>
  <textarea name= "profile"></textarea><br>
  <input type="submit" name="送信">
<% end %>

app/views/companies/new.html.erb
<header>
  <div class="top-header">
    <div class="row">
      <div class="col-md-offset-2 col-md-2 logo">
        <%= link_to "地魚マーケット","/top/index", class: 'logo' %>
      </div>
      <div class="col-md-2 l-btn">
      　<%= link_to "業者様ログイン","/top/company_login", class: 'btn-l'%>
      </div>
      <div class="col-md-2 l-btn">       
        <%= link_to "お客様ログイン","/top/user_login", class: 'btn-l'%>
      </div>
    </div>
  </div>
</header>
<div class="top-wrapper">
  <%= form_tag("/companies",{multipart: true}) do %> 
    <div class="c_login col-md-offset-5 col-md-2">
        <p class='text-white'>会社名</p>
        <input name="company_name" >
        <p class='text-white'>Eメール</p>
        <input name="email">
        <p class='text-white'>電話番号</p>
        <input name="phone_number">
        <p class='text-white'>住所</p>
        <input name="address">
        <p class='text-white'>パスワード</p>
        <input type="password" name="password" placeholder="半角英数字8~32文字">
        <p class='text-white'>買参権の写真</p>
        <input name="image_name" type="file">
        <input type="submit" value="新規登録">
    </div>
  <% end %>
</div>
  

app/views/companies/point.html.erb
<h>総売上ポイント</h><br>
<% if @company.point.present? %>
  <%= @company.point %>
  <%= form_tag("/companies/transfer") do%>
  <%= submit_tag"振り込み依頼をする" %>
  <% end %>
<% else %>
  <h>0 pt</h><br>
<% end %>
<h>過去の振り込み一覧</h><br>
<% @records.each do |record| %>
  <h><%= record.created_at.strftime('%Y/%m/%d') %>日</h><br>
  <h><%= record.record %>ptの振り込み依頼をしました。</h><br>
<% end %>

app/views/companies/show.html.erb
<div class="c-show text-center">
    <p>
      <%= notice %>
    </p>
    <p>
      <img src ="<%= current_company.profile_image %>">
    </p>
    <p>
      <%= current_company.company_name %>
    </p>
    <p>
      <%= current_company.address %>
    </p>
    <p>
      <%= current_company.phone_number %>
    </p>
    <p>
      <%= current_company.profile %>
    </p>
    <%= link_to "プロフィール編集", edit_company_path %>
    <% @topics.each do |topic| %>
      <p>
        <%= topic.content %><br>
      </p>
      <div class="row">
        <div class="col-md-offset-5 col-md-2">
            <%= image_tag topic.image_name.url %>
        </div>
      </div>
      <%= topic.price %><br>
      <p>
        <%= topic.created_at.strftime("%Y-%m-%d %H:%M") %>
      </p>
    <% end %>
</div>

app/views/companies/trade.html.erb
<% @topics.each do |topic| %>
  <img src="<%=topic.image_name%>"><br>
  <%= topic.content %><br>
  <%= topic.price %><br>
  <h>お客様が購入した時刻です。</h><br>
  <%= topic.time.strftime("%Y-%m-%d %H:%M") %><br>
  <% if !topic.point.present? %>
    <% if topic.address.present? %>
      <h>送付先住所</h><br>
      <%= topic.address %><br>
      <%= link_to("配送しました","/companies/#{topic.id}/ship", {method: :post}) %><br>
    <% else %>
      <h>配送は完了しました！</h><br>
    <% end %>
  <% else %>
    <h>取引が完了しました！</h><br>
  <% end %>
<% end %>

<% @replies.each do |reply| %>
  <img src="<%=reply.image_name%>"><br>
  <%= reply.content %><br>
  <%= reply.price %><br>
  <h>購入した時刻</h><br>
  <%= reply.time.strftime("%Y-%m-%d %H:%M") %><br>
  <% if !reply.point.present? %>
    <% if reply.address.present? %>
      <h>送付先住所</h><br>
      <%= reply.address %><br>
      <%= link_to("配送しました","/companies/#{reply.id}/reply_ship", {method: :post}) %><br>
    <% else %>
      <h>配送は完了しました！</h><br>
    <% end %>
  <% else %>
    <h>取引が完了しました！</h><br>
  <% end %>
<% end %>